Currently got an issue in extending to 3 scalar fields: ./UserVariables.hpp:45:59: error: excess elements in struct initializer     user_variable_names = {"phi1", "phi2", "phi3", "Pi1", "Pi2", "Pi3"};
Think this is due to NUM_VARS being incorrect but not 100% sure